language: go

go:
  - 1.13
  - 1.12
git:
  depth: 1

install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/lint/golint
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - golint .
  - go test -cover -race -count=1 -timeout=2m -run .
  # - go test -run=Bench.* -bench=. -benchmem